/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DocsRouteImport } from './routes/docs/route'
import { Route as IndexImport } from './routes/index'
import { Route as GalleryIndexImport } from './routes/gallery/index'
import { Route as Gallery2024Import } from './routes/gallery/2024'
import { Route as DocsSlugImport } from './routes/docs/$slug'
import { Route as SinglePageTodoImport } from './routes/_single-page/todo'
import { Route as SinglePageConstructingImport } from './routes/_single-page/constructing'
import { Route as SinglePageAboutImport } from './routes/_single-page/about'

// Create/Update Routes

const DocsRouteRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const GalleryIndexRoute = GalleryIndexImport.update({
  id: '/gallery/',
  path: '/gallery/',
  getParentRoute: () => rootRoute,
} as any)

const Gallery2024Route = Gallery2024Import.update({
  id: '/gallery/2024',
  path: '/gallery/2024',
  getParentRoute: () => rootRoute,
} as any)

const DocsSlugRoute = DocsSlugImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DocsRouteRoute,
} as any)

const SinglePageTodoRoute = SinglePageTodoImport.update({
  id: '/_single-page/todo',
  path: '/todo',
  getParentRoute: () => rootRoute,
} as any)

const SinglePageConstructingRoute = SinglePageConstructingImport.update({
  id: '/_single-page/constructing',
  path: '/constructing',
  getParentRoute: () => rootRoute,
} as any)

const SinglePageAboutRoute = SinglePageAboutImport.update({
  id: '/_single-page/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRoute
    }
    '/_single-page/about': {
      id: '/_single-page/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SinglePageAboutImport
      parentRoute: typeof rootRoute
    }
    '/_single-page/constructing': {
      id: '/_single-page/constructing'
      path: '/constructing'
      fullPath: '/constructing'
      preLoaderRoute: typeof SinglePageConstructingImport
      parentRoute: typeof rootRoute
    }
    '/_single-page/todo': {
      id: '/_single-page/todo'
      path: '/todo'
      fullPath: '/todo'
      preLoaderRoute: typeof SinglePageTodoImport
      parentRoute: typeof rootRoute
    }
    '/docs/$slug': {
      id: '/docs/$slug'
      path: '/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof DocsSlugImport
      parentRoute: typeof DocsRouteImport
    }
    '/gallery/2024': {
      id: '/gallery/2024'
      path: '/gallery/2024'
      fullPath: '/gallery/2024'
      preLoaderRoute: typeof Gallery2024Import
      parentRoute: typeof rootRoute
    }
    '/gallery/': {
      id: '/gallery/'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface DocsRouteRouteChildren {
  DocsSlugRoute: typeof DocsSlugRoute
}

const DocsRouteRouteChildren: DocsRouteRouteChildren = {
  DocsSlugRoute: DocsSlugRoute,
}

const DocsRouteRouteWithChildren = DocsRouteRoute._addFileChildren(
  DocsRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteRouteWithChildren
  '/about': typeof SinglePageAboutRoute
  '/constructing': typeof SinglePageConstructingRoute
  '/todo': typeof SinglePageTodoRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/gallery/2024': typeof Gallery2024Route
  '/gallery': typeof GalleryIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteRouteWithChildren
  '/about': typeof SinglePageAboutRoute
  '/constructing': typeof SinglePageConstructingRoute
  '/todo': typeof SinglePageTodoRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/gallery/2024': typeof Gallery2024Route
  '/gallery': typeof GalleryIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteRouteWithChildren
  '/_single-page/about': typeof SinglePageAboutRoute
  '/_single-page/constructing': typeof SinglePageConstructingRoute
  '/_single-page/todo': typeof SinglePageTodoRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/gallery/2024': typeof Gallery2024Route
  '/gallery/': typeof GalleryIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/about'
    | '/constructing'
    | '/todo'
    | '/docs/$slug'
    | '/gallery/2024'
    | '/gallery'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs'
    | '/about'
    | '/constructing'
    | '/todo'
    | '/docs/$slug'
    | '/gallery/2024'
    | '/gallery'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/_single-page/about'
    | '/_single-page/constructing'
    | '/_single-page/todo'
    | '/docs/$slug'
    | '/gallery/2024'
    | '/gallery/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRouteRoute: typeof DocsRouteRouteWithChildren
  SinglePageAboutRoute: typeof SinglePageAboutRoute
  SinglePageConstructingRoute: typeof SinglePageConstructingRoute
  SinglePageTodoRoute: typeof SinglePageTodoRoute
  Gallery2024Route: typeof Gallery2024Route
  GalleryIndexRoute: typeof GalleryIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRouteRoute: DocsRouteRouteWithChildren,
  SinglePageAboutRoute: SinglePageAboutRoute,
  SinglePageConstructingRoute: SinglePageConstructingRoute,
  SinglePageTodoRoute: SinglePageTodoRoute,
  Gallery2024Route: Gallery2024Route,
  GalleryIndexRoute: GalleryIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/docs",
        "/_single-page/about",
        "/_single-page/constructing",
        "/_single-page/todo",
        "/gallery/2024",
        "/gallery/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/docs": {
      "filePath": "docs/route.tsx",
      "children": [
        "/docs/$slug"
      ]
    },
    "/_single-page/about": {
      "filePath": "_single-page/about.tsx"
    },
    "/_single-page/constructing": {
      "filePath": "_single-page/constructing.tsx"
    },
    "/_single-page/todo": {
      "filePath": "_single-page/todo.tsx"
    },
    "/docs/$slug": {
      "filePath": "docs/$slug.tsx",
      "parent": "/docs"
    },
    "/gallery/2024": {
      "filePath": "gallery/2024.tsx"
    },
    "/gallery/": {
      "filePath": "gallery/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
